V8 upgrade
hyphacoop/testnets pull request #1
Opened 2022-08-23 20:43 UTC by dasanchez

- Renamed the testnet folders
- Updated info on the Theta public and local testnet pages.
- Upgrade dates still TBD

2022-09-01 17:02 UTC, uditvira requested changes

2022-09-01 17:02 UTC, uditvira commented on README.md
> +**Starting with `Theta`, we have moved to a persistent testnet model, which means the `Theta` testnet will stay online and remain the primary Cosmos Hub testnet after the `v7-Theta` upgrade and beyon
```suggestion
**Starting with `Theta`, we have moved to a persistent testnet model. The`Theta` testnet will stay online and remain the primary Cosmos Hub testnet after the `v7-Theta` upgrade, including for the v8-Rho and v9-Lambda upgrades, and beyond**
```

2022-09-01 17:02 UTC, uditvira commented on theta/public-testnet/UPGRADES.md
> +
remove extra lines?

2022-09-14 18:14 UTC, uditvira commented
@ASoTNetworks can you update the devnet information?

2022-09-19 14:16 UTC, dasanchez commented
Closing this PR to open one against `cosmos/testnets`

2022-09-19 14:16 UTC, closed without merging